# This is a workflow to convert rmd file to a Jupyter notebook format. Allows rendered rmd documents to be available in GitHub repo.

# Controls when the action will run. Workflow runs changes are pushed to any branch
on:
  push:
    paths:
      - "**.rmd"

name: RMD to ipynb workflow
jobs:
  convert_rmd_to_ipynb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U notebook
          python -m pip install -U jupytext
      - name: Install a Jupyter Kernel
        run: python -m ipykernel install --name python_kernel --user
      - name: Check if RMarkdown file is in the commit
      - uses: dorny/paths-filter@v2
        id: filter
        with:
        # Enable listing of files matching each filter.
        # Paths to files will be available in `${FILTER_NAME}_files` output variable.
        # Paths will be escaped and space-delimited.
        # Output is usable as command-line argument list in Linux shell
          list-files: shell
          filters: |
            rmarkdown:
              - added|modified: '*.rmd'
      - name: Convert Notebook
        if: ${{ steps.filter.outputs.rmarkdown == 'true' }}
        run: |
          jupytext --to ipynb ${{ steps.filter.outputs.rmarkdown_files }}
          git add --all
          git commit -m "build notebook from Rmarkdown files"
          git push origin
